In [1]:
import numpy as np

### set seed

In [2]:
np.random.seed(123) #Create a random seed to aid in reproducibility

### set random state which is independent from the global seed

| Feature | Random Seed (Legacy) | Random State (Modern) |
| :--- | :--- | :--- |
| **Abstraction** | Initial integer input | Encapsulating object |
| **Control Level** | **Global:** Affects all future random calls. | **Local:** Creates an isolated, independent source of randomness. |
| **Reproducibility** | Guarantees global reproducibility. | Guarantees reproducibility **within the scope of the object**. |
| **Concurrency** | **Not thread-safe:** Risky in multi-threaded code as multiple threads could interfere with the global state. | **Thread-safe:** You can pass an isolated `Generator` object to each thread without interference. |

In [3]:
rs = np.random.RandomState(321) # create a random state object
rs.rand(10) # generate 10 random numbers

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

### generate a random sample from interval [0, 1) in a given shape

In [4]:
rs = np.random.RandomState(321) # create a random state object, try using other values to see how the rs.rand() value changes
# generate a random scalar
print(rs.rand()) # generate a random scalar     

0.8859479412560747


In [5]:
rs = np.random.RandomState(321) # create a random state object
# generate a 1-D array
print(rs.rand(3)) # generate a 1-D array          

[0.88594794 0.07791236 0.97964616]


In [6]:
rs = np.random.RandomState(321) # create a random state object

# generate a 2-D array
print(rs.rand(3,3))   # generate a 2-D array that is 3x3

[[0.88594794 0.07791236 0.97964616]
 [0.24767146 0.75288472 0.52667564]
 [0.90755375 0.8840703  0.08926896]]


### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [7]:
rs = np.random.RandomState(321) # create a random state object
# generate a 2-D array from standard normal distribution
print(rs.randn(3,3)) # replace rs with np.random.randn to a random standard normal distribution

[[ 0.17251947  1.63548253  0.0373364 ]
 [-0.88414969 -1.14319226 -0.62136604]
 [-1.34864958 -0.81973103 -0.1342539 ]]


### generate an array of random integers in a given interval [low, high)

In [ ]:
rs = np.random.RandomState(321) # create a random state object
# np.ranodm.randint(low, high, size, dtype)
print(rs.randint(1, 10, 3, 'i8')) # replace rs with np.random.randn to get different random integers between 1 and 10

[5 9 2]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [16]:
rs = np.random.RandomState(321) 
# the following methods are the same as np.random.rand()
print(rs.random_sample(10)) # generate 10 random numbers, random_sample is an alias for random
rs = np.random.RandomState(321) 
print(rs.random(10)) # generate 10 random numbers, random is an alias for random_sample


[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472 0.52667564
 0.90755375 0.8840703  0.08926896 0.5173446 ]
[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472 0.52667564
 0.90755375 0.8840703  0.08926896 0.5173446 ]


### generate a random sample from a given 1-D array

In [17]:
rs = np.random.RandomState(321) # create a random state object
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(rs.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1])) # use rs.choice to make an array of 10 with a range of 0-2 and specified probabilities

[1 0 2 1 1 1 2 1 0 1]


In [ ]:
for i in range(3): # loop to print values 0, 1, 2
    print(i) # loop to print values 0, 1, 2

0
1
2


In [24]:
rs = np.random.RandomState(321) # create a random state object
print(rs.choice(3, 10)) #use random choice to make an array of 10 with a range of 0-2

[0 2 0 1 0 1 0 2 0 0]


In [25]:
rs = np.random.RandomState(321) # create a random state object
print(rs.choice([1,2,3], 10)) # use random choice to make an array of 10 from the given list

[1 3 1 2 1 2 1 3 1 1]


### shuffle an array in place

In [35]:
arr = np.array(range(10)) # create an array from 0 to 9
print(arr) # print the array from 0 to 9

[0 1 2 3 4 5 6 7 8 9]


In [28]:
np.random.shuffle(arr) # shuffles the array in-place
print(arr)

[9 5 6 0 7 4 3 8 1 2]


In [38]:
arr = np.array(range(10)) # create an array from 0 to 9
print(arr) # print the array from 0 to 9

rs = np.random.RandomState(321) # create a random state object
rs.shuffle(arr) # shuffles the array in-place
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[5 3 7 9 6 2 0 1 8 4]


### generate a permutation of an array

In [ ]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10)) # create an array from 0 to 9
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr)) # prints a permutation of the array without changing the original array

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [4 6 2 5 7 1 0 8 9 3]


# Exercise

## Exercise 1
**Synthetic Data Auditing** Generate a synthetic dataset representing 10 different sensors, each taking 20 readings. To ensure your teammate gets the exact same results as you, you must use a seed.

**TaskGenerate:** Create a $10 \times 20$ array of random floats between 0 and 1.Requirement: Use np.random.seed(42) (or the newer Generator method) to make the numbers reproducible.

Inspect: Print the following properties of your array:

* The shape (dimensions).
* The size (total number of elements). 
* The ndim (number of dimensions).
* The dtype (data type of the elements).

**Validate:** Access the element at the very last row and last column. If your seed is correct, this value should be approximately 0.075

Next [Module](./5.%20Math%20Functions.ipynb)

In [4]:
import numpy as np
rng = np.random.default_rng(42)   # choose any integer seed
arr = rng.random((10, 20)) 
print(arr)

[[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735 0.97562235
  0.7611397  0.78606431 0.12811363 0.45038594 0.37079802 0.92676499
  0.64386512 0.82276161 0.4434142  0.22723872 0.55458479 0.06381726
  0.82763117 0.6316644 ]
 [0.75808774 0.35452597 0.97069802 0.89312112 0.7783835  0.19463871
  0.466721   0.04380377 0.15428949 0.68304895 0.74476216 0.96750973
  0.32582536 0.37045971 0.46955581 0.18947136 0.12992151 0.47570493
  0.22690935 0.66981399]
 [0.43715192 0.8326782  0.7002651  0.31236664 0.8322598  0.80476436
  0.38747838 0.2883281  0.6824955  0.13975248 0.1999082  0.00736227
  0.78692438 0.66485086 0.70516538 0.78072903 0.45891578 0.5687412
  0.139797   0.11453007]
 [0.66840296 0.47109621 0.56523611 0.76499886 0.63471832 0.5535794
  0.55920716 0.3039501  0.03081783 0.43671739 0.21458467 0.40852864
  0.85340307 0.23393949 0.05830274 0.28138389 0.29359376 0.66191651
  0.55703215 0.78389821]
 [0.66431354 0.40638686 0.81402038 0.16697292 0.02271207 0.09004786
  0.72235935 0.461